### ISSUE TITLE
Peering Request

### ISSUE THREAD

**Issue by kjartanhr** [routeviews/issues#41] opened 2022-10-28 16:47 UTC
### Full Name

Kjartan Hrafnkelsson

### ASN

AS208548

### PeeringDB Integration

- [X] My PeeringDB Entries are current
- [ ] Peer at ***all available exchanges*** (and omit Peer Address(es) field below)

### Peer Address(es)

185.1.167.126 2001:7f8:f2:e1:0:20:8548:1

### Code of Conduct (TODO)

- [X] I agree to follow this project's Code of Conduct

**Comment by pfsinoz** [comment] 2024-04-20 17:06
Thank you for your interest in the RouteViews project. 

Please confirm what peering with RouteViews you are looking for - KTT Anycast Services is not present in any DC or IXP according to your PeeringDB entry. We are assuming EBGP multihop to the stated addresses. Please let us know if you are still interested in going ahead, and then we can work on this with you.

Thanks!

**Comment by elinarbur** [comment] 2024-04-20 17:34
Hi and thank you for the response.

Having done some network-related changes in the last two year since submitting this request, the ASN we will peer from is AS51019 (https://www.peeringdb.com/asn/51019). Route Views AS6447 is present on a mutual exchange, LOCIX Frankfurt - 185.1.167.72 - 2001:7f8:f2:e1::6447:1, where peering could be initiated. We can also peer over eBGP multihop as suggested if capacity is an issue in this location.

Definitely interested in going ahead with this!

Best,
Kjartan

**Comment by pfsinoz** [comment] 2024-04-21 15:26
Hi Kjartan,

Capacity is a bit of an issue for us at LOCIX Frankfurt (as it is for multi-hops too), but let's see how we go. I've set it up at LOCIX, and this is the current status of the peering on our collector:
```
Neighbor        V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
185.1.167.88    4      51019         0         3        0    0    0    never       Active        0 Kjartannet
Neighbor                     V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
2001:7f8:f2:e1:0:5:1019:1    4      51019         0         3        0    0    0    never       Active        0 Kjartannet
```
Please filter out default route and RFC6490 address space. 
NOTE: we do not accept addpath-RX or TX on connections.

Thanks and best wishes!

**Comment by elinarbur** [comment] 2024-04-21 17:31
Hi again,

I configured standard filters (reject RPKI invalid, length invalid, RFC6490, etc) in addition to specifically making sure to never send a default route.

I see both sessions as `Established`. Let me know if anyhing else is required from my end (maybe if we need to switch to multihop) I'll be happy to adjust asap.

Thanks!
Kjartan

**Comment by pfsinoz** [comment] 2024-04-21 18:51
Hi Kjartan,

Confirmed we see them both up and running now:
```
185.1.167.88    4      51019     59860       137        0    0    0 01:09:41       178914        0 Kjartannet
2001:7f8:f2:e1:0:5:1019:1    4      51019     93791       137        0    0    0 01:09:39       198701        0 Kjartannet
```
Looking good. Let's see how we go there, hopefully we haven't overloaded the collector in doing this. Will be in touch if we need to move to multihop.

Best wishes,
Philip

**Closed by pfsinoz** 2024-04-21 18:51 UTC
